### PR TITLE
Update `aliquot-pay` version to `2.1.0`

### PR DESCRIPTION
**Pull request by cbobach**

### CODE REVIEW

**Review by mt-clearhaus — APPROVED** [review]
:+1:

**Comment by mt-clearhaus** [comment]
Aah. I didn't spot the issue with a cyclic dependency. However, my approval still stands.

**Comment by cbobach** [comment]
@mt-clearhaus I've added a new commit which removes the version pump of `aliquot` itself. I've done this because of the cyclic dependency we have between `aloqout` -> `aliquot-pay` -> `aliquot`.

I think the best solution would be to `yank` the existing `aliquot:2.1.0` gem and publish a new one to sync dependencies.

Do you have any thoughts on this?

**Comment by mt-clearhaus** [comment]
I'm no expert here but it sounds reasonable :+1:

**Comment by ct-clearhaus** [comment]
Some discussion in `#tech-pci` https://clearhaus.slack.com/archives/C3LG75WE9/p1662708113155469 🙂

**Pull request merged**
